# Generated by Django 5.2.8 on 2025-11-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='weight_percentage',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='weight_percentage',
        ),
    ]
