# Generated by Django 5.2.8 on 2025-12-09 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weight_percentage',
            field=models.FloatField(blank=True, help_text='Weight as percentage relative to sprint total (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
