# Generated by Django 5.2.8 on 2025-12-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_task_weight_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
