# Generated by Django 4.2 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_add_task_to_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='weight_percentage',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('deadline', 'Deadline'), ('assignment', 'Assignment'), ('comment', 'Comment'), ('member_added', 'Member Added'), ('status_change', 'Status Change'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
