# Generated by Django 4.2 on 2026-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_remove_weight_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='health_status',
            field=models.CharField(blank=True, choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('critical', 'Critical')], default='on_track', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='health_status',
            field=models.CharField(blank=True, choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('critical', 'Critical')], default='on_track', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='health_status',
            field=models.CharField(blank=True, choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('critical', 'Critical')], default='on_track', max_length=20, null=True),
        ),
    ]
