# Generated by Django 4.2 on 2026-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_milestone_health_status_project_health_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('deadline', 'Deadline'), ('assignment', 'Assignment'), ('comment', 'Comment'), ('member_added', 'Member Added'), ('status_change', 'Status Change'), ('health_degradation', 'Health Degradation'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
