# Generated by Django 4.2 on 2026-05-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_add_checklist_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_done_state', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_statuses', to='pm.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
