# Generated by Django 4.2 on 2026-05-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_customfielddefinition_taskcustomfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('status_change', 'Status Change'), ('due_date_passed', 'Due Date Passed'), ('task_created', 'Task Created'), ('assignee_changed', 'Assignee Changed')], max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('send_notification', 'Send Notification'), ('change_status', 'Change Status'), ('change_priority', 'Change Priority'), ('assign_to', 'Assign To')], max_length=50)),
                ('action_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='pm.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
