# Generated by Django 4.2 on 2026-05-19 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0020_goal_goaltarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_priority', models.CharField(default='Medium', max_length=20)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('custom_field_defaults', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('default_tags', models.ManyToManyField(blank=True, related_name='task_templates', to='pm.tag')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='pm.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
