# Generated by Django 4.2 on 2026-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0021_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
