# Generated by Django 4.2 on 2026-05-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_workspacemember_is_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=20)),
                ('repo_url', models.URLField()),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_integrations', to='pm.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'repo_url')},
            },
        ),
        migrations.CreateModel(
            name='TaskGitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_url', models.URLField(blank=True)),
                ('pr_number', models.PositiveIntegerField(blank=True, null=True)),
                ('pr_title', models.CharField(blank=True, max_length=500)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.gitintegration')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_links', to='pm.task')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
