# Generated by Django 4.2 on 2026-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_git_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ical_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
